services:
  bot:
    build: .
    container_name: fnnews_bot
    network_mode: host
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    restart: unless-stopped
